@url = http://localhost:5500
@api = /api/v1

### Hello World!

GET {{ url }} HTTP/1.1
Content-type: application/json

###
# @name courses

GET {{ url }}{{ api }}/database/course HTTP/1.1
Content-type: application/json

###

@course_id = {{ courses.response.body.data[0].id }}

GET {{ url }}{{ api }}/database/course/{{ course_id }} HTTP/1.1
Content-type: application/json

###

POST {{ url }}{{ api }}/database/course HTTP/1.1
Content-type: application/json

{
  "nome": "Curso 1",
  "descricao": "Descricao 1"
}

###

PUT {{ url }}{{ api }}/database/course/{{ course_id }} HTTP/1.1
Content-type: application/json

{
  "nome": "Curso Alterado",
  "descricao": "Descricao 1"
}

### Lista de alunos no curso

GET {{ url }}{{ api }}/database/course/{{ course_id }}/enroll HTTP/1.1
Content-type: application/json

### Matricular aluno no curso

POST {{ url }}{{ api }}/database/course/{{ course_id }}/enroll HTTP/1.1
Content-type: application/json

###
# @name students

GET {{ url }}{{ api }}/database/student HTTP/1.1
Content-type: application/json

###

@student_id = {{ students.response.body.data[0].id }}

GET {{ url }}{{ api }}/database/student/{{ student_id }} HTTP/1.1
Content-type: application/json

###

POST {{ url }}{{ api }}/database/student HTTP/1.1
Content-type: application/json

{
  "nome": "Aluno 10",
  "email": "aluno10@gmail.com",
  "dataNascimento": "2010-01-01"
}

###

PUT {{ url }}{{ api }}/database/student/{{ student_id }} HTTP/1.1
Content-type: application/json

{
  "nome": "Curso 20",
  "email": "aluno_20@gmail.com",
  "dataNascimento": "2010-01-01"
}

### Lista de curso do aluno

GET {{ url }}{{ api }}/database/student/{{ student_id }}/enroll HTTP/1.1
Content-type: application/json
