version: "3.3"

services:
  database:
    image: postgres
    container_name: database-curso
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=curso-user
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=curso-db
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local

networks:
  default:
    driver: bridge
